bucket                  = "<target_account_state_bucket>"
key                     = "<target_account_state_key>"
region                  = "<target_region>"
dynamodb_table          = "<target_account_dynamodb_table>"
assume_role.role_arn    = "<target_role_arn>"
assume_role.external_id = "<external_id>"
