variable "account_name" {
  description = "Per-customer unique slug. Generated by Java via DeploymentService.generateUniqueAccountName (max 63 chars). Used in resource names so all tenants coexist in one Cloudflare account."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]{1,63}$", var.account_name))
    error_message = "account_name must be 1-63 chars, lowercase alphanumeric and hyphens only."
  }
}

variable "cloudflare_account" {
  description = "Cloudflare account configuration. Phase 1 uses the Staticbot-owned account; Phase 2 will pass per-customer values from their IntegrationInstance."
  type = object({
    account_id = string
    api_token  = string
  })
  sensitive = true
}

variable "shared_infra" {
  description = "References to shared account-level infra (from the account_bootstrap module outputs). Java pulls these from tf-worker env vars set after `cloudflare/environments/prod` apply."
  type = object({
    dispatch_namespace_name = string
    dispatch_namespace_id   = string
    routes_kv_namespace_id  = string
    zone_id                 = string
    fallback_hostname       = string
  })
}

variable "app" {
  description = "Per-customer app configuration."
  type = object({
    worker_name       = string                    # WfP user-Worker name (e.g., "<account_name>-app")
    customer_hostname = string                    # Customer's domain (e.g., "app.acme.com" or "acme.com")
    plain_env         = optional(map(string), {}) # Non-sensitive env vars exposed to the Worker
  })
}

variable "worker_secrets" {
  description = "Sensitive env vars pushed via `wrangler secret put` after deploy. Stored encrypted in worker_jobs_queue.vars; the wrangler_deploy step decrypts and pipes to wrangler. Defined here so TF can declare placeholder bindings."
  type        = map(string)
  sensitive   = true
  default     = {}
}

variable "common_tags" {
  description = "Resource tags. Cloudflare doesn't support tags broadly, but kept for parity with other templates and for future CF audit metadata."
  type        = map(string)
  default = {
    ManagedBy = "Staticbot"
  }
}
